
services:
  # 1. BASE DE DATOS
  mongo:
    image: mongo:latest
    container_name: mensajeria
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. BACKEND (Node.js)
  server:
    build: ./server
    container_name: chat-server
    ports:
      - "3000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-e2ee
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  # 3. FRONTEND (React + Vite)
  client:
    build: ./client
    container_name: chat-client
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data: